[tool.poetry]
name = "dadinhoserver"
version = "0.1.0"
description = ""
authors = ["Barradas13 <febarradas13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.122.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
